name: football_ai_frontend
description: A new Flutter project for Football AI Insights.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.2
  file_picker: ^8.0.0
  http: ^1.2.0
  audioplayers: ^5.2.1
  image_picker: ^1.2.1
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
